run:
  delivery: False

# paths
workspace_path: 'results'
path_bed: '/scratch/giulia.pontali/genomics_QC_pipeline/results_scratch/bed/qc_recoded_harmonised'
bed_template: 'impute_recoded_selected_sample_filter_hq_var_new_id_alleles_{chrom}.bed'
bim_template: 'impute_recoded_selected_sample_filter_hq_var_new_id_alleles_{chrom}.bim'
fam_template: 'impute_recoded_selected_sample_filter_hq_var_new_id_alleles_{chrom}.fam'
path_seqids: 'config/path_seqids.txt'
path_sumstats: '/exchange/healthds/pQTL/results/META_CHRIS_INTERVAL/qced_sumstats_digits_not_flipped/output/'
suffix: '*.gwaslab.tsv.bgz'

ldsc_dict:
  window: 10000



